# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RiviumPushExample' do
  config = use_native_modules!

  pod 'MqttCocoaAsyncSocket', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix fmt consteval compilation error with Xcode 26+
    fmt_base_h = File.join(__dir__, 'Pods', 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base_h)
      content = File.read(fmt_base_h)
      unless content.include?('FMT_USE_CONSTEVAL_PATCHED')
        content.gsub!(
          '#elif defined(__cpp_consteval)',
          "#elif 1 // FMT_USE_CONSTEVAL_PATCHED: disable consteval for Xcode 26+\n#  define FMT_USE_CONSTEVAL 0\n#elif defined(__cpp_consteval)"
        )
        File.write(fmt_base_h, content)
      end
    end
  end
end
