#!/usr/bin/env node
/**
 * Keeps src/version.ts in sync with package.json.
 *
 *   node scripts/sync-version.js          write src/version.ts
 *   node scripts/sync-version.js --check  exit 1 if it is out of date
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const { version } = require(path.join(root, 'package.json'));
const target = path.join(root, 'src', 'version.ts');

const expected =
  '// Generated by scripts/sync-version.js from package.json. Do not edit.\n' +
  "export const SDK_NAME = 'react-native';\n" +
  `export const SDK_VERSION = '${version}';\n`;

const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';

if (process.argv.includes('--check')) {
  if (current !== expected) {
    console.error(`src/version.ts is out of date (package.json is ${version}). Run: node scripts/sync-version.js`);
    process.exit(1);
  }
  console.log(`src/version.ts matches package.json (${version})`);
} else if (current !== expected) {
  fs.writeFileSync(target, expected);
  console.log(`src/version.ts updated to ${version}`);
}
